<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType Condition="'$(PublishSingleFile)' == 'true'">none</DebugType>
    <DebugSymbols Condition="'$(PublishSingleFile)' == 'true'">false</DebugSymbols>
  </PropertyGroup>
</Project>
